[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/mk"
  status = 302
  force = true
  conditions = {Language = ["mk"]}

[[redirects]]
  from = "/"
  to = "/sq"
  status = 302
  force = true
  conditions = {Language = ["sq"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 